# ============================================================
#  ESPHome – Raspberry Pi Pico W + WireGuard (remote sensor)
#  Parameter names are identical to the official component:
#  https://esphome.io/components/wireguard/
# ============================================================

esphome:
  name: pico-remote
  friendly_name: "Pico W Remote Sensor"
  # Need change optimalization otherwise crypto lib x25519 crash during executing
  platformio_options:
    build_type: debug
    debug_build_flags:
      - -O2       # Keep high optimization for small binary size
      - -g1       # Minimal debug info: gives file names and line numbers only
rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/earlephilhower/arduino-pico/releases/download/4.1.1/package_rp2040_index.json

external_components:
  - source:
      type: local
      path: esphome/components
    components: [wireguard]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.6.0.2   # must match wireguard address below

time:
  - platform: sntp
    id: sntp_time
    servers:
      - pool.ntp.org

# ============================================================
#  WireGuard – same YAML keys as the official component
# ============================================================
wireguard:
  id: wg
  time_id: sntp_time

  address: 10.6.0.2
  netmask: 255.255.255.0

  private_key: !secret wg_private_key
  peer_endpoint: !secret wg_server_host
  peer_public_key: !secret wg_server_pubkey
  peer_port: 51820

  # peer_preshared_key: !secret wg_preshared_key   # optional

  peer_allowed_ips:
    - 0.0.0.0/0   # full tunnel – all traffic through VPN

  peer_persistent_keepalive: 25s
  reboot_timeout: 15min

  status:
    name: "WireGuard Status"
  enabled:
    name: "WireGuard Enabled"
  latest_handshake:
    name: "WireGuard Latest Handshake"

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: WARNING

sensor:
  - platform: internal_temperature
    name: "RP2040 Internal Temperature"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GP15
      mode: INPUT_PULLUP
    name: "Remote Switch"
    device_class: door

switch:
  - platform: gpio
    pin: GP14
    name: "Remote Relay"
    restore_mode: RESTORE_DEFAULT_OFF
